# Generated by Django 6.0.5 on 2026-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('div', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('img', models.ImageField(upload_to='stdentimage')),
            ],
        ),
    ]
